mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
routing-mark: 7894
allow-lan: true
bind-address: "*"
ipv6: true
mode: rule
unified-delay: true
tcp-concurrent: true
find-process-mode: off
log-level: info
geodata-loader: standard
external-controller: :9999
disable-keep-alive: true
profile:
  store-selected: true
proxy-groups:
  - name: 选择代理
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 自动选择
      - 故障转移
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 手动选择
      - DIRECT
  - name: 手动选择
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    proxies: &a1
      - 选择代理
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 手动选择
      - DIRECT
  - name: AI服务
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ChatGPT.png
    type: select
    proxies: *a1
  - name: 加密货币
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cryptocurrency_1.png
    type: select
    proxies: *a1
  - name: 苹果服务
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple_2.png
    type: select
    proxies: *a1
  - name: 谷歌服务
    icon: https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/Google.png
    type: select
    proxies: *a1
  - name: 微软服务
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Microsoft_Copilot.png
    type: select
    proxies: *a1
  - name: Xbox
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Xbox.png
    type: select
    proxies: *a1
  - name: Github
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    type: select
    proxies: *a1
  - name: 哔哩哔哩
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies:
      - DIRECT
      - 台湾节点
      - 香港节点
  - name: 巴哈姆特
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bahamut.png
    type: select
    proxies:
      - 台湾节点
      - 选择代理
      - 手动选择
      - DIRECT
  - name: Youtube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies: *a1
  - name: Twitch
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    type: select
    proxies: *a1
  - name: Netflix
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies: *a1
  - name: TikTok
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    type: select
    proxies: *a1
  - name: Spotify
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    type: select
    proxies: *a1
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Telegram.png
    type: select
    proxies: *a1
  - name: Twitter
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    type: select
    proxies: *a1
  - name: 新浪微博
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Weibo.png
    type: select
    include-all: true
    proxies:
      - DIRECT
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 选择代理
      - 手动选择
  - name: Truth Social
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Truth_Social.png
    type: select
    proxies:
      - 美国节点
      - 选择代理
      - 手动选择
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies: *a1
  - name: PikPak网盘
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/PikPak.png
    type: select
    proxies: *a1
  - name: 搜狗输入法
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Sougou.png
    type: select
    proxies:
      - DIRECT
      - REJECT
  - name: SSH
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Server.png
    type: select
    proxies: *a1
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - REJECT-DROP
      - DIRECT
  - name: Final
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - 选择代理
      - DIRECT
  - name: 自动选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    url: https://cp.cloudflare.com
    proxies: &a2
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
    interval: 60
    tolerance: 20
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png
    type: fallback
    url: https://cp.cloudflare.com
    proxies: *a2
    interval: 60
    tolerance: 20
  - name: 低倍率节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lab.png
    type: select
    include-all: true
    filter: (?i)0\.[0-5]|低倍率|省流|实验性
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    type: select
    include-all: true
    filter: 香港|港|\b(?:HK|hk)(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Hong
      Kong|HongKong|hongkong|HONG
      KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌|🇭🇰
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    type: select
    include-all: true
    filter: 台|新北|彰化|\b(?:TW|tw)(?:[-_ ]?\d+(?:[-_
      ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC|🇹🇼|🇼🇸
  - name: 新加坡节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    type: select
    include-all: true
    filter: 新加坡|坡|狮城|\b(?:SG|sg)(?:[-_ ]?\d+(?:[-_
      ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN|🇸🇬
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    type: select
    include-all: true
    filter: 日本|川日|东京|大阪|泉日|埼玉|沪日|深日|\b(?:JP|jp)(?:[-_ ]?\d+(?:[-_
      ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI|🇯🇵
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    type: select
    include-all: true
    filter: 美国|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|亚特兰大|迈阿密|华盛顿|\b(?:US|us)(?:[-_
      ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED
      STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC|🇺🇸
    exclude-filter: 美属|亚美尼亚|圣多美|普林西比
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - 选择代理
      - 手动选择
      - 静态资源
      - AI服务
      - 加密货币
      - 苹果服务
      - 谷歌服务
      - 微软服务
      - Xbox
      - Github
      - 哔哩哔哩
      - 巴哈姆特
      - Youtube
      - Twitch
      - Netflix
      - TikTok
      - Spotify
      - Telegram
      - Twitter
      - 新浪微博
      - Truth Social
      - E-Hentai
      - PikPak网盘
      - 搜狗输入法
      - SSH
      - 广告拦截
      - Final
      - 自动选择
      - 故障转移
      - 低倍率节点
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: yaml
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.yaml
    path: ./ruleset/ADBlock.yaml
  AWAvenue:
    type: http
    behavior: domain
    format: yaml
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-Clash.yaml
    path: ./ruleset/AWAvenue.yaml
  adblockmihomo:
    type: http
    behavior: domain
    format: yaml
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomo.yaml
    path: ./ruleset/adblockmihomo.yaml
  SogouInput:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.txt
  StaticResources:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./ruleset/StaticResources.txt
  CDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./ruleset/CDNResources.txt
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TikTok.list
    path: ./ruleset/TikTok.list
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list
  GoogleFCM:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
    path: ./ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list
  AdditionalCDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalCDNResources.list
    path: ./ruleset/AdditionalCDNResources.list
  Crypto:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/Crypto.list
    path: ./ruleset/Crypto.list
  Weibo:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/Weibo.list
    path: ./ruleset/Weibo.list
  GFWList:
    type: http
    behavior: domain
    format: yaml
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/GFWList.yaml
  direct:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt
    path: ./ruleset/direct.txt
  reject:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/reject-list.txt
    path: ./ruleset/reject.txt
  proxy:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/proxy-list.txt
    path: ./ruleset/proxy.txt
rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT
  - DST-PORT,22,SSH
  - GEOIP,private,DIRECT,no-resolve
  - RULE-SET,AWAvenue,广告拦截
  - RULE-SET,adblockmihomo,广告拦截
  - RULE-SET,ADBlock,广告拦截
  - RULE-SET,AdditionalFilter,广告拦截
  - RULE-SET,reject,广告拦截
  - RULE-SET,SogouInput,搜狗输入法
  - DOMAIN-SUFFIX,truthsocial.com,Truth Social
  - RULE-SET,StaticResources,静态资源
  - RULE-SET,CDNResources,静态资源
  - RULE-SET,AdditionalCDNResources,静态资源
  - GEOSITE,category-ai-!cn,AI服务
  - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,youtube,Youtube
  - GEOSITE,telegram,Telegram
  - GEOIP,telegram,Telegram,no-resolve
  - GEOSITE,xbox,Xbox
  - GEOSITE,github,Github
  - GEOSITE,netflix,Netflix
  - GEOSITE,twitch,Twitch
  - GEOIP,netflix,Netflix,no-resolve
  - GEOSITE,spotify,Spotify
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,pikpak,PikPak网盘
  - GEOSITE,twitter,Twitter
  - RULE-SET,Weibo,新浪微博
  - RULE-SET,EHentai,E-Hentai
  - RULE-SET,TikTok,TikTok
  - RULE-SET,SteamFix,DIRECT
  - RULE-SET,GoogleFCM,DIRECT
  - GEOSITE,google-play@cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple,苹果服务
  - GEOSITE,microsoft,微软服务
  - GEOSITE,google,谷歌服务
  - RULE-SET,Crypto,加密货币
  - RULE-SET,GFWList,选择代理
  - GEOIP,cn,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,选择代理
  - MATCH,Final
sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
    QUIC:
      ports:
        - 443
        - 8443
  override-destination: false
  enable: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - system
    - 223.5.5.5
    - 119.29.29.29
    - 180.184.1.1
  fallback:
    - quic://dns0.eu
    - https://dns.cloudflare.com/dns-query
    - https://dns.sb/dns-query
    - tcp://208.67.222.222
    - tcp://8.26.56.2
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - tls://dot.pub
tun:
  enable: false
  stack: gvisor
  device: mihomo
  route-exclude-address:
    - 100.64.0.0/10
    - fd7a:115c:a1e0::/48
    - 192.168.0.0/16
    - fd00::/8
  dns-hijack:
    - any:53
  mtu: 1500
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb

